collections:

    - name: ibm.cloudcollection
    - name: azure.azcollection
    - name: awx.awx
    - name: amazon.aws
    - name: google.cloud
    - src: https://github.com/geerlingguy/ansible-role-apache

