---
- name: create index.html
  hosts: tag_Name_Web
  tasks:   
     - name: Create index.html using Jinja2
       template:
        src: ../../templates/index.j2
        dest: /var/www/html/index.html
