- name: ec2 provisioning 
  hosts: localhost
  connection: local
  become: False
  tasks:
  - name: launch ec2
    ec2:
     instance_type: "{{ ec2_instance_type }}"
     key_name: aws-tower.pub
     image: ami-7c491f05
     region: "{{ ec2_region }}"
     group: "{{ ec2_security_group }}"
     count: "{{ ec2_instance_count }}"
     count_tag: 
           Name: fazi_ops
     vpc_subnet_id: "{{ vpc_subnet_id }}" 
     wait: yes
     assign_public_ip: yes 
