- name: ec2 stop
  hosts: localhost
  connection: local
  become: False
  
  tasks:
  - name: stop ec2
    ec2:
     region: "{{ ec2_region }}"
     group: "{{ ec2_security_group }}"
     state: stopped
