---
- name: Terminate instances
  hosts: all
  vars:
    region: eu-west-1
  tasks:
    - name: Terminate instances that were previously launched
      amazon.aws.ec2:
        region: "{{ region }}"
        state: 'absent'
        instance_ids: '{{ ec2.instance_ids }}'
        







 